import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* 依照依賴順序載入 */}
        <Script
          src="https://code.jquery.com/jquery-3.5.1.min.js"
          strategy="beforeInteractive"
        />
        <Script
          src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"
          strategy="beforeInteractive"
        />
        <Script
          src="https://cdn.webrtc-experiment.com/MediaStreamRecorder.js"
          strategy="beforeInteractive"
        />
        <Script
          src={process.env.NEXT_PUBLIC_ASUS_SPEECH_RECOGNITION_LIB}
          strategy="beforeInteractive"
        />
        {/* <Script
          src="/js/Asus_SpeechRecognition.js"
          strategy="beforeInteractive"
        /> */}
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div style={{ width: "100vw", height: "100vh" }}>{children}</div>
      </body>
    </html>
  );
}
